package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1

/**
 * Associados generated by hbm2java
 */
public class Associados implements java.io.Serializable {

    private int idAssociado;
    private String nomeAssociado;
    private String cpfAssociado;
    private String rgAssociado;
    private String cidadeAssociado;
    private Short endNum;
    private String endRua;
    private String endBairro;
    private String uf;
    private String endComplemento;

    public Associados() {
    }

    public Associados(int idAssociado) {
        this.idAssociado = idAssociado;
    }

    public Associados(int idAssociado, String nomeAssociado, String cpfAssociado, String rgAssociado, String cidadeAssociado, Short endNum, String endRua, String endBairro, String uf, String endComplemento) {
        this.idAssociado = idAssociado;
        this.nomeAssociado = nomeAssociado;
        this.cpfAssociado = cpfAssociado;
        this.rgAssociado = rgAssociado;
        this.cidadeAssociado = cidadeAssociado;
        this.endNum = endNum;
        this.endRua = endRua;
        this.endBairro = endBairro;
        this.uf = uf;
        this.endComplemento = endComplemento;
    }

    public Associados(String nomeAssociado, String cpfAssociado, String rgAssociado, String cidadeAssociado, Short endNum, String endRua, String endBairro, String uf, String endComplemento) {
        this.nomeAssociado = nomeAssociado;
        this.cpfAssociado = cpfAssociado;
        this.rgAssociado = rgAssociado;
        this.cidadeAssociado = cidadeAssociado;
        this.endNum = endNum;
        this.endRua = endRua;
        this.endBairro = endBairro;
        this.uf = uf;
        this.endComplemento = endComplemento;
    }

    public String getNomeAssociado() {
        return nomeAssociado;
    }

    public void setNomeAssociado(String nomeAssociado) {
        this.nomeAssociado = nomeAssociado;
    }

    public int getIdAssociado() {
        return this.idAssociado;
    }

    public void setIdAssociado(int idAssociado) {
        this.idAssociado = idAssociado;
    }

    public String getCpfAssociado() {
        return this.cpfAssociado;
    }

    public void setCpfAssociado(String cpfAssociado) {
        this.cpfAssociado = cpfAssociado;
    }

    public String getRgAssociado() {
        return this.rgAssociado;
    }

    public void setRgAssociado(String rgAssociado) {
        this.rgAssociado = rgAssociado;
    }

    public Short getEndNum() {
        return this.endNum;
    }

    public void setEndNum(Short endNum) {
        this.endNum = endNum;
    }

    public String getEndRua() {
        return this.endRua;
    }

    public void setEndRua(String endRua) {
        this.endRua = endRua;
    }

    public String getEndBairro() {
        return this.endBairro;
    }

    public void setEndBairro(String endBairro) {
        this.endBairro = endBairro;
    }

    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    public String getCidadeAssociado() {
        return cidadeAssociado;
    }

    public void setCidadeAssociado(String cidadeAssociado) {
        this.cidadeAssociado = cidadeAssociado;
    }

    public String getEndComplemento() {
        return endComplemento;
    }

    public void setEndComplemento(String endComplemento) {
        this.endComplemento = endComplemento;
    }

}
