package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1



/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private int idEmpresa;
     private String nomeEmpresa;
     private String cnpj;

    public Empresas() {
    }

	
    public Empresas(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Empresas(int idEmpresa, String nomeEmpresa, String cnpj) {
       this.idEmpresa = idEmpresa;
       this.nomeEmpresa = nomeEmpresa;
       this.cnpj = cnpj;
    }
   
    public Empresas(String nomeEmpresa, String cnpj) {
       this.nomeEmpresa = nomeEmpresa;
       this.cnpj = cnpj;
    }
    
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNomeEmpresa() {
        return this.nomeEmpresa;
    }
    
    public void setNomeEmpresa(String nomeEmpresa) {
        this.nomeEmpresa = nomeEmpresa;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }




}


