package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1

import java.util.ArrayList;

/**
 * ItensVendidos generated by hbm2java
 */
public class ItensVendidos implements java.io.Serializable {

    private int id;
    private ArrayList<Vendas> vendas;

    public ItensVendidos(int id, ArrayList<Vendas> carrinho) {
        this.id = id;
        this.vendas = carrinho;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public ArrayList<Vendas> getVendas() {
        return vendas;
    }

    public void setVendas(ArrayList<Vendas> vendas) {
        this.vendas = vendas;
    }
}
