package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1

import java.util.ArrayList;

/**
 * ItensComprados generated by hbm2java
 */
public class ItensComprados implements java.io.Serializable {

    private int id;
    private ArrayList<Compras> compras;

    public ItensComprados(int id, ArrayList<Compras> carrinho) {
        this.id = id;
        this.compras = carrinho;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public ArrayList<Compras> getCompras() {
        return compras;
    }

    public void setCompras(ArrayList<Compras> compras) {
        this.compras = compras;
    }
    
}
