package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1



/**
 * ItensVendidosId generated by hbm2java
 */
public class ItensVendidosId  implements java.io.Serializable {


     private int idMaterial;
     private long idVenda;

    public ItensVendidosId() {
    }

    public ItensVendidosId(int idMaterial, long idVenda) {
       this.idMaterial = idMaterial;
       this.idVenda = idVenda;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public long getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(long idVenda) {
        this.idVenda = idVenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItensVendidosId) ) return false;
		 ItensVendidosId castOther = ( ItensVendidosId ) other; 
         
		 return (this.getIdMaterial()==castOther.getIdMaterial())
 && (this.getIdVenda()==castOther.getIdVenda());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMaterial();
         result = 37 * result + (int) this.getIdVenda();
         return result;
   }   


}


