package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1



/**
 * ItensComprados generated by hbm2java
 */
public class ItensComprados  implements java.io.Serializable {


     private ItensCompradosId id;
     private Compras compras;
     private Materiais materiais;
     private Double quantidadekg;
     private Double precokg;
     private Double precoTotal;

    public ItensComprados() {
    }

	
    public ItensComprados(ItensCompradosId id, Compras compras, Materiais materiais) {
        this.id = id;
        this.compras = compras;
        this.materiais = materiais;
    }
    public ItensComprados(ItensCompradosId id, Compras compras, Materiais materiais, Double quantidadekg, Double precokg, Double precoTotal) {
       this.id = id;
       this.compras = compras;
       this.materiais = materiais;
       this.quantidadekg = quantidadekg;
       this.precokg = precokg;
       this.precoTotal = precoTotal;
    }
   
    public ItensCompradosId getId() {
        return this.id;
    }
    
    public void setId(ItensCompradosId id) {
        this.id = id;
    }
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    public Materiais getMateriais() {
        return this.materiais;
    }
    
    public void setMateriais(Materiais materiais) {
        this.materiais = materiais;
    }
    public Double getQuantidadekg() {
        return this.quantidadekg;
    }
    
    public void setQuantidadekg(Double quantidadekg) {
        this.quantidadekg = quantidadekg;
    }
    public Double getPrecokg() {
        return this.precokg;
    }
    
    public void setPrecokg(Double precokg) {
        this.precokg = precokg;
    }
    public Double getPrecoTotal() {
        return this.precoTotal;
    }
    
    public void setPrecoTotal(Double precoTotal) {
        this.precoTotal = precoTotal;
    }




}


