package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1



/**
 * ItensVendidos generated by hbm2java
 */
public class ItensVendidos  implements java.io.Serializable {


     private ItensVendidosId id;
     private Materiais materiais;
     private Vendas vendas;
     private Double quantidadekg;
     private Double precokg;
     private Double precototal;

    public ItensVendidos() {
    }

	
    public ItensVendidos(ItensVendidosId id, Materiais materiais, Vendas vendas) {
        this.id = id;
        this.materiais = materiais;
        this.vendas = vendas;
    }
    public ItensVendidos(ItensVendidosId id, Materiais materiais, Vendas vendas, Double quantidadekg, Double precokg, Double precototal) {
       this.id = id;
       this.materiais = materiais;
       this.vendas = vendas;
       this.quantidadekg = quantidadekg;
       this.precokg = precokg;
       this.precototal = precototal;
    }
   
    public ItensVendidosId getId() {
        return this.id;
    }
    
    public void setId(ItensVendidosId id) {
        this.id = id;
    }
    public Materiais getMateriais() {
        return this.materiais;
    }
    
    public void setMateriais(Materiais materiais) {
        this.materiais = materiais;
    }
    public Vendas getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }
    public Double getQuantidadekg() {
        return this.quantidadekg;
    }
    
    public void setQuantidadekg(Double quantidadekg) {
        this.quantidadekg = quantidadekg;
    }
    public Double getPrecokg() {
        return this.precokg;
    }
    
    public void setPrecokg(Double precokg) {
        this.precokg = precokg;
    }
    public Double getPrecototal() {
        return this.precototal;
    }
    
    public void setPrecototal(Double precototal) {
        this.precototal = precototal;
    }




}


