package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1



/**
 * ItensCompradosId generated by hbm2java
 */
public class ItensCompradosId  implements java.io.Serializable {


     private int idMaterial;
     private long idCompra;

    public ItensCompradosId() {
    }

    public ItensCompradosId(int idMaterial, long idCompra) {
       this.idMaterial = idMaterial;
       this.idCompra = idCompra;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public long getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(long idCompra) {
        this.idCompra = idCompra;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItensCompradosId) ) return false;
		 ItensCompradosId castOther = ( ItensCompradosId ) other; 
         
		 return (this.getIdMaterial()==castOther.getIdMaterial())
 && (this.getIdCompra()==castOther.getIdCompra());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMaterial();
         result = 37 * result + (int) this.getIdCompra();
         return result;
   }   


}


