package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposDespesas generated by hbm2java
 */
public class TiposDespesas  implements java.io.Serializable {


     private int idTipo;
     private String tituloTipo;
     private Set despesases = new HashSet(0);

    public TiposDespesas() {
    }

	
    public TiposDespesas(int idTipo) {
        this.idTipo = idTipo;
    }
    public TiposDespesas(int idTipo, String tituloTipo, Set despesases) {
       this.idTipo = idTipo;
       this.tituloTipo = tituloTipo;
       this.despesases = despesases;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getTituloTipo() {
        return this.tituloTipo;
    }
    
    public void setTituloTipo(String tituloTipo) {
        this.tituloTipo = tituloTipo;
    }
    public Set getDespesases() {
        return this.despesases;
    }
    
    public void setDespesases(Set despesases) {
        this.despesases = despesases;
    }




}


