package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendas generated by hbm2java
 */
public class Vendas  implements java.io.Serializable {


     private long idVenda;
     private Integer idEmpresa;
     private Boolean notaFiscal;
     private Set itensVendidoses = new HashSet(0);

    public Vendas() {
    }

	
    public Vendas(long idVenda) {
        this.idVenda = idVenda;
    }
    public Vendas(long idVenda, Integer idEmpresa, Boolean notaFiscal, Set itensVendidoses) {
       this.idVenda = idVenda;
       this.idEmpresa = idEmpresa;
       this.notaFiscal = notaFiscal;
       this.itensVendidoses = itensVendidoses;
    }
   
    public long getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(long idVenda) {
        this.idVenda = idVenda;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Boolean getNotaFiscal() {
        return this.notaFiscal;
    }
    
    public void setNotaFiscal(Boolean notaFiscal) {
        this.notaFiscal = notaFiscal;
    }
    public Set getItensVendidoses() {
        return this.itensVendidoses;
    }
    
    public void setItensVendidoses(Set itensVendidoses) {
        this.itensVendidoses = itensVendidoses;
    }




}


