/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import acari.modeloTabelaAssociados;
import acari.modeloTabelaEmpresas;
import controller.principalController;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.Associados;
import model.Empresas;

public class principalViewVelha extends javax.swing.JFrame {

    boolean onFullScreen = false;
    principalController principalControlador;

    public principalViewVelha() {

        this.principalControlador = new principalController();//Cria o controlador principal o qual ira inicializar todos os outros
        initComponents();
        this.setLocationRelativeTo(null);

        //inicializa e coloca o logo (imagem) no canto superior esquerdo
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("logoProject.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(logoLabel.getWidth(), logoLabel.getHeight(),
                Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        logoLabel.setIcon(imageIcon);

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Tem certeza que quer sair?") == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });

    }

    public boolean closeWindow() {
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que quer sair?") == 0) {
            return true;//cierra aplicacion
        }
        return false;
    }

    public void setFullScreen() {
        if (!onFullScreen) {
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            onFullScreen = true;
        } else {
            this.setExtendedState(JFrame.NORMAL);
            onFullScreen = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        pagIniPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comprarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoCompraTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cancelarCompraButton = new javax.swing.JButton();
        confirmarCompraButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        totalAPagarLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        associadoComboBox = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        materialCompraComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        precoItemCompraTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        quantidadeItemCompraTextField = new javax.swing.JTextField();
        cadastrarNovoMaterialCompraButton = new javax.swing.JButton();
        adicionarItemCompraButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        precoTotalItemTextField = new javax.swing.JTextField();
        cadastrarAssociadoCompraButton = new javax.swing.JButton();
        venderPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoVendaTextArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        cancelarVendaButton = new javax.swing.JButton();
        confirmarVendaButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        infoVendaTotalAReceberLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        empresasComboBox = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        materialVendaComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        precoItemVendaTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        quantidadeItemVendaTextField = new javax.swing.JTextField();
        CadastrarNovoMaterialVendaButton = new javax.swing.JButton();
        adicionarItemVendaButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        precoTotalItemVendaTextField = new javax.swing.JTextField();
        cadastrarNovaEmpresaAuxButtonAux = new javax.swing.JButton();
        relatoriosPanel = new javax.swing.JPanel();
        associadosPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        excluirAssociadoListaButton = new javax.swing.JButton();
        cadastrarNovoAssociadoListaButton = new javax.swing.JButton();
        editarAssociadoListaButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssociados = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        empresasPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        excluirEmpresaListaButton = new javax.swing.JButton();
        cadastrarEmpresaListaButton = new javax.swing.JButton();
        editarEmpresaListaButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEmpresas = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        menuButtonsPanel = new javax.swing.JPanel();
        pagIniButton = new javax.swing.JButton();
        comprarButton = new javax.swing.JButton();
        venderButton = new javax.swing.JButton();
        relatoriosButton = new javax.swing.JButton();
        associadosButton = new javax.swing.JButton();
        empresasButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setPreferredSize(new java.awt.Dimension(1300, 650));

        infoPanel.setBackground(new java.awt.Color(204, 255, 204));
        infoPanel.setPreferredSize(new java.awt.Dimension(1141, 620));
        infoPanel.setLayout(new java.awt.CardLayout());

        pagIniPanel.setBackground(new java.awt.Color(255, 255, 255));
        pagIniPanel.setPreferredSize(new java.awt.Dimension(1141, 730));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/acariApresentacao.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("® Desenvolvido por Ruan M. Adabo & Ian M. Tobar");

        javax.swing.GroupLayout pagIniPanelLayout = new javax.swing.GroupLayout(pagIniPanel);
        pagIniPanel.setLayout(pagIniPanelLayout);
        pagIniPanelLayout.setHorizontalGroup(
            pagIniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pagIniPanelLayout.setVerticalGroup(
            pagIniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagIniPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        infoPanel.add(pagIniPanel, "card2");

        comprarPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Informações do Item");

        infoCompraTextArea.setBackground(new java.awt.Color(255, 255, 255));
        infoCompraTextArea.setColumns(20);
        infoCompraTextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        infoCompraTextArea.setRows(5);
        infoCompraTextArea.setText("AOSKDADMADPSASDPLASD\nAPSDKMADSM\nlaksdmmnkad\nlkansdkadmçlasmas\n\napçskdmpçkasdmpçasdmkçasd\nasd\nad\nsaçdmklsçkadmsaçkdms\nad\nadslakmnsdklmadskads\nads\nadskasmndsklmads");
        jScrollPane1.setViewportView(infoCompraTextArea);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Informações da Compra");

        cancelarCompraButton.setBackground(new java.awt.Color(156, 36, 33));
        cancelarCompraButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cancelarCompraButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelarCompraButton.setText("Cancelar");
        cancelarCompraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCompraButtonActionPerformed(evt);
            }
        });

        confirmarCompraButton.setBackground(new java.awt.Color(1, 103, 204));
        confirmarCompraButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        confirmarCompraButton.setForeground(new java.awt.Color(51, 51, 51));
        confirmarCompraButton.setText("Confirmar");

        totalAPagarLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        totalAPagarLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalAPagarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAPagarLabel.setText("Total a Pagar: R$0000,00");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Associado:");

        associadoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        associadoComboBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        associadoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        associadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Seixas dos Santos da Silva", "Flora Guenzburguer Baumann Somogyi", "Item 3", "Item 4" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Preço Por Kilo (em Reais):");

        materialCompraComboBox.setBackground(new java.awt.Color(255, 255, 255));
        materialCompraComboBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        materialCompraComboBox.setForeground(new java.awt.Color(0, 0, 0));
        materialCompraComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor de Geladeira", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Material:");

        precoItemCompraTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        precoItemCompraTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precoItemCompraTextField.setText("00,00");
        precoItemCompraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoItemCompraTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Quantidade (em Kilos):");

        quantidadeItemCompraTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        quantidadeItemCompraTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidadeItemCompraTextField.setText("00000");
        quantidadeItemCompraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeItemCompraTextFieldActionPerformed(evt);
            }
        });

        cadastrarNovoMaterialCompraButton.setBackground(new java.awt.Color(51, 153, 0));
        cadastrarNovoMaterialCompraButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cadastrarNovoMaterialCompraButton.setForeground(new java.awt.Color(33, 57, 8));
        cadastrarNovoMaterialCompraButton.setText("Cadastrar Novo Material");
        cadastrarNovoMaterialCompraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovoMaterialCompraButtonActionPerformed(evt);
            }
        });

        adicionarItemCompraButton.setBackground(new java.awt.Color(51, 153, 0));
        adicionarItemCompraButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adicionarItemCompraButton.setForeground(new java.awt.Color(33, 57, 8));
        adicionarItemCompraButton.setText("Adicionar Item");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Preço Total (em Reais):");

        precoTotalItemTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        precoTotalItemTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precoTotalItemTextField.setText("0000,00");
        precoTotalItemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoTotalItemTextFieldActionPerformed(evt);
            }
        });

        cadastrarAssociadoCompraButton.setBackground(new java.awt.Color(51, 153, 0));
        cadastrarAssociadoCompraButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cadastrarAssociadoCompraButton.setForeground(new java.awt.Color(33, 57, 8));
        cadastrarAssociadoCompraButton.setText("Cadastrar Novo Associado");
        cadastrarAssociadoCompraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAssociadoCompraButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comprarPanelLayout = new javax.swing.GroupLayout(comprarPanel);
        comprarPanel.setLayout(comprarPanelLayout);
        comprarPanelLayout.setHorizontalGroup(
            comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(associadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(materialCompraComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cadastrarAssociadoCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(cadastrarNovoMaterialCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(quantidadeItemCompraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(precoItemCompraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(precoTotalItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(adicionarItemCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(comprarPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalAPagarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmarCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(791, 791, 791)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        comprarPanelLayout.setVerticalGroup(
            comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(associadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialCompraComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarAssociadoCompraButton)
                    .addComponent(cadastrarNovoMaterialCompraButton))
                .addGap(70, 70, 70)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeItemCompraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(comprarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoItemCompraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(precoTotalItemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(adicionarItemCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(totalAPagarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(confirmarCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(cancelarCompraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(comprarPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        infoPanel.add(comprarPanel, "card2");

        venderPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Informações do Item");

        infoVendaTextArea.setBackground(new java.awt.Color(255, 255, 255));
        infoVendaTextArea.setColumns(20);
        infoVendaTextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        infoVendaTextArea.setRows(5);
        infoVendaTextArea.setText("AOSKDADMADPSASDPLASD\nAPSDKMADSM\nlaksdmmnkad\nlkansdkadmçlasmas\n\napçskdmpçkasdmpçasdmkçasd\nasd\nad\nsaçdmklsçkadmsaçkdms\nad\nadslakmnsdklmadskads\nads\nadskasmndsklmads");
        jScrollPane4.setViewportView(infoVendaTextArea);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Informações da Venda");

        cancelarVendaButton.setBackground(new java.awt.Color(156, 36, 33));
        cancelarVendaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cancelarVendaButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelarVendaButton.setText("Cancelar");

        confirmarVendaButton.setBackground(new java.awt.Color(1, 103, 204));
        confirmarVendaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        confirmarVendaButton.setForeground(new java.awt.Color(51, 51, 51));
        confirmarVendaButton.setText("Confirmar");

        infoVendaTotalAReceberLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        infoVendaTotalAReceberLabel.setForeground(new java.awt.Color(0, 0, 0));
        infoVendaTotalAReceberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoVendaTotalAReceberLabel.setText("Total a Receber: R$0000,00");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Empresa");

        empresasComboBox.setBackground(new java.awt.Color(255, 255, 255));
        empresasComboBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        empresasComboBox.setForeground(new java.awt.Color(0, 0, 0));
        empresasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Seixas dos Santos da Silva", "Flora Guenzburguer Baumann Somogyi", "Item 3", "Item 4" }));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Preço Por Kilo (em Reais):");

        materialVendaComboBox.setBackground(new java.awt.Color(255, 255, 255));
        materialVendaComboBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        materialVendaComboBox.setForeground(new java.awt.Color(0, 0, 0));
        materialVendaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor de Geladeira", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Material");

        precoItemVendaTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        precoItemVendaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precoItemVendaTextField.setText("00,00");
        precoItemVendaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoItemVendaTextFieldActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Quantidade (em Kilos):");

        quantidadeItemVendaTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        quantidadeItemVendaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidadeItemVendaTextField.setText("00000");
        quantidadeItemVendaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeItemVendaTextFieldActionPerformed(evt);
            }
        });

        CadastrarNovoMaterialVendaButton.setBackground(new java.awt.Color(51, 153, 0));
        CadastrarNovoMaterialVendaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CadastrarNovoMaterialVendaButton.setForeground(new java.awt.Color(33, 57, 8));
        CadastrarNovoMaterialVendaButton.setText("Cadastrar Novo Material");
        CadastrarNovoMaterialVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarNovoMaterialVendaButtonActionPerformed(evt);
            }
        });

        adicionarItemVendaButton.setBackground(new java.awt.Color(51, 153, 0));
        adicionarItemVendaButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adicionarItemVendaButton.setForeground(new java.awt.Color(33, 57, 8));
        adicionarItemVendaButton.setText("Adicionar Item");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Preço Total (em Reais):");

        precoTotalItemVendaTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        precoTotalItemVendaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precoTotalItemVendaTextField.setText("0000,00");
        precoTotalItemVendaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoTotalItemVendaTextFieldActionPerformed(evt);
            }
        });

        cadastrarNovaEmpresaAuxButtonAux.setBackground(new java.awt.Color(51, 153, 0));
        cadastrarNovaEmpresaAuxButtonAux.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cadastrarNovaEmpresaAuxButtonAux.setForeground(new java.awt.Color(33, 57, 8));
        cadastrarNovaEmpresaAuxButtonAux.setText("Cadastrar Nova Empresa");
        cadastrarNovaEmpresaAuxButtonAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovaEmpresaAuxButtonAuxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout venderPanelLayout = new javax.swing.GroupLayout(venderPanel);
        venderPanel.setLayout(venderPanelLayout);
        venderPanelLayout.setHorizontalGroup(
            venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empresasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarNovaEmpresaAuxButtonAux, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(precoTotalItemVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(materialVendaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CadastrarNovoMaterialVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(precoItemVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(quantidadeItemVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(adicionarItemVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(410, 410, 410)
                .addGroup(venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmarVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(infoVendaTotalAReceberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(790, 790, 790)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        venderPanelLayout.setVerticalGroup(
            venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGroup(venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(empresasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cadastrarNovaEmpresaAuxButtonAux)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precoTotalItemVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(materialVendaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CadastrarNovoMaterialVendaButton))
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(precoItemVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(quantidadeItemVendaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionarItemVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(venderPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(confirmarVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cancelarVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(venderPanelLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(infoVendaTotalAReceberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        infoPanel.add(venderPanel, "card2");

        javax.swing.GroupLayout relatoriosPanelLayout = new javax.swing.GroupLayout(relatoriosPanel);
        relatoriosPanel.setLayout(relatoriosPanelLayout);
        relatoriosPanelLayout.setHorizontalGroup(
            relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1141, Short.MAX_VALUE)
        );
        relatoriosPanelLayout.setVerticalGroup(
            relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        infoPanel.add(relatoriosPanel, "card2");

        associadosPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Lista de Associados");

        excluirAssociadoListaButton.setBackground(new java.awt.Color(156, 36, 33));
        excluirAssociadoListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        excluirAssociadoListaButton.setForeground(new java.awt.Color(56, 22, 20));
        excluirAssociadoListaButton.setText("Excluir Associado");
        excluirAssociadoListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAssociadoListaButtonActionPerformed(evt);
            }
        });

        cadastrarNovoAssociadoListaButton.setBackground(new java.awt.Color(51, 153, 0));
        cadastrarNovoAssociadoListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cadastrarNovoAssociadoListaButton.setForeground(new java.awt.Color(33, 57, 8));
        cadastrarNovoAssociadoListaButton.setText("Cadastrar Novo Associado");
        cadastrarNovoAssociadoListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovoAssociadoListaButtonActionPerformed(evt);
            }
        });

        editarAssociadoListaButton.setBackground(new java.awt.Color(204, 204, 0));
        editarAssociadoListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        editarAssociadoListaButton.setForeground(new java.awt.Color(51, 51, 0));
        editarAssociadoListaButton.setText("Editar Associado");
        editarAssociadoListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAssociadoListaButtonActionPerformed(evt);
            }
        });

        jTableAssociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "RG", "Rua", "Número", "Complemento", "Bairro", "Cidade", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAssociados);
        if (jTableAssociados.getColumnModel().getColumnCount() > 0) {
            jTableAssociados.getColumnModel().getColumn(1).setHeaderValue("CPF");
            jTableAssociados.getColumnModel().getColumn(2).setHeaderValue("RG");
            jTableAssociados.getColumnModel().getColumn(3).setHeaderValue("Rua");
            jTableAssociados.getColumnModel().getColumn(4).setHeaderValue("Número");
            jTableAssociados.getColumnModel().getColumn(5).setHeaderValue("Complemento");
            jTableAssociados.getColumnModel().getColumn(6).setHeaderValue("Bairro");
            jTableAssociados.getColumnModel().getColumn(7).setHeaderValue("Cidade");
            jTableAssociados.getColumnModel().getColumn(8).setHeaderValue("UF");
        }

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Pesquisa por Nome:");

        javax.swing.GroupLayout associadosPanelLayout = new javax.swing.GroupLayout(associadosPanel);
        associadosPanel.setLayout(associadosPanelLayout);
        associadosPanelLayout.setHorizontalGroup(
            associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(associadosPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(editarAssociadoListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(associadosPanelLayout.createSequentialGroup()
                .addGap(740, 740, 740)
                .addComponent(excluirAssociadoListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(associadosPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(cadastrarNovoAssociadoListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(associadosPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(associadosPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(associadosPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        associadosPanelLayout.setVerticalGroup(
            associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(associadosPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(associadosPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarAssociadoListaButton)
                            .addComponent(excluirAssociadoListaButton)
                            .addComponent(cadastrarNovoAssociadoListaButton))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        infoPanel.add(associadosPanel, "card2");

        empresasPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Lista de Empresas");

        excluirEmpresaListaButton.setBackground(new java.awt.Color(156, 36, 33));
        excluirEmpresaListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        excluirEmpresaListaButton.setForeground(new java.awt.Color(56, 22, 20));
        excluirEmpresaListaButton.setText("Excluir Empresa");
        excluirEmpresaListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEmpresaListaButtonActionPerformed(evt);
            }
        });

        cadastrarEmpresaListaButton.setBackground(new java.awt.Color(51, 153, 0));
        cadastrarEmpresaListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cadastrarEmpresaListaButton.setForeground(new java.awt.Color(33, 57, 8));
        cadastrarEmpresaListaButton.setText("Cadastrar Nova Empresa");
        cadastrarEmpresaListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEmpresaListaButtonActionPerformed(evt);
            }
        });

        editarEmpresaListaButton.setBackground(new java.awt.Color(204, 204, 0));
        editarEmpresaListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        editarEmpresaListaButton.setForeground(new java.awt.Color(51, 51, 0));
        editarEmpresaListaButton.setText("Editar Empresa");
        editarEmpresaListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpresaListaButtonActionPerformed(evt);
            }
        });

        jTableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "CNPJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableEmpresas);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Pesquisa por Nome:");

        javax.swing.GroupLayout empresasPanelLayout = new javax.swing.GroupLayout(empresasPanel);
        empresasPanel.setLayout(empresasPanelLayout);
        empresasPanelLayout.setHorizontalGroup(
            empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(empresasPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(cadastrarEmpresaListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empresasPanelLayout.createSequentialGroup()
                .addGap(740, 740, 740)
                .addComponent(excluirEmpresaListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empresasPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(editarEmpresaListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(empresasPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(empresasPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(empresasPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        empresasPanelLayout.setVerticalGroup(
            empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empresasPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(empresasPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrarEmpresaListaButton)
                            .addComponent(excluirEmpresaListaButton)
                            .addComponent(editarEmpresaListaButton))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        infoPanel.add(empresasPanel, "card2");

        menuPanel.setBackground(new java.awt.Color(50, 165, 54));

        menuButtonsPanel.setBackground(new java.awt.Color(50, 165, 54));
        menuButtonsPanel.setLayout(new java.awt.GridLayout(7, 1));

        pagIniButton.setBackground(new java.awt.Color(50, 144, 55));
        pagIniButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pagIniButton.setForeground(new java.awt.Color(0, 0, 0));
        pagIniButton.setText("Pagina Inicial");
        pagIniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagIniButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(pagIniButton);

        comprarButton.setBackground(new java.awt.Color(50, 144, 55));
        comprarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comprarButton.setForeground(new java.awt.Color(0, 0, 0));
        comprarButton.setText("Comprar");
        comprarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(comprarButton);

        venderButton.setBackground(new java.awt.Color(50, 144, 55));
        venderButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        venderButton.setForeground(new java.awt.Color(0, 0, 0));
        venderButton.setText("Vender");
        venderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(venderButton);

        relatoriosButton.setBackground(new java.awt.Color(50, 144, 55));
        relatoriosButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        relatoriosButton.setForeground(new java.awt.Color(0, 0, 0));
        relatoriosButton.setText("Relatórios");
        menuButtonsPanel.add(relatoriosButton);

        associadosButton.setBackground(new java.awt.Color(50, 144, 55));
        associadosButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        associadosButton.setForeground(new java.awt.Color(0, 0, 0));
        associadosButton.setText("Associados");
        associadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associadosButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(associadosButton);

        empresasButton.setBackground(new java.awt.Color(50, 144, 55));
        empresasButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        empresasButton.setForeground(new java.awt.Color(0, 0, 0));
        empresasButton.setText("Empresas");
        empresasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresasButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(empresasButton);

        sairButton.setBackground(new java.awt.Color(50, 144, 55));
        sairButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sairButton.setForeground(new java.awt.Color(0, 0, 0));
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(sairButton);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(comprarPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
    }//GEN-LAST:event_comprarButtonActionPerformed

    private void pagIniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagIniButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(pagIniPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
    }//GEN-LAST:event_pagIniButtonActionPerformed

    private void precoItemCompraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoItemCompraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoItemCompraTextFieldActionPerformed

    private void quantidadeItemCompraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeItemCompraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeItemCompraTextFieldActionPerformed

    private void cadastrarNovoMaterialCompraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoMaterialCompraButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarNovoMaterialCompraButtonActionPerformed

    private void precoTotalItemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoTotalItemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoTotalItemTextFieldActionPerformed

    private void associadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associadosButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(associadosPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
        preencherTabela("Associados", jTableAssociados);
    }//GEN-LAST:event_associadosButtonActionPerformed

    private void empresasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresasButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(empresasPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
        preencherTabela("Empresas", jTableEmpresas);
    }//GEN-LAST:event_empresasButtonActionPerformed

    private void precoItemVendaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoItemVendaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoItemVendaTextFieldActionPerformed

    private void quantidadeItemVendaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeItemVendaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeItemVendaTextFieldActionPerformed

    private void CadastrarNovoMaterialVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarNovoMaterialVendaButtonActionPerformed
        //new fichaMaterialForm().setVisible(true);
    }//GEN-LAST:event_CadastrarNovoMaterialVendaButtonActionPerformed

    private void precoTotalItemVendaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoTotalItemVendaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoTotalItemVendaTextFieldActionPerformed

    private void venderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(venderPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
    }//GEN-LAST:event_venderButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        if (closeWindow()) {
            this.dispose();
        }
    }//GEN-LAST:event_sairButtonActionPerformed

    private void cadastrarAssociadoCompraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAssociadoCompraButtonActionPerformed
        //new fichaAssociadoForm(principalControlador, null, this);
    }//GEN-LAST:event_cadastrarAssociadoCompraButtonActionPerformed

    private void cancelarCompraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCompraButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(pagIniPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
    }//GEN-LAST:event_cancelarCompraButtonActionPerformed

    private void cadastrarNovaEmpresaAuxButtonAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovaEmpresaAuxButtonAuxActionPerformed
       // new fichaEmpresaForm(principalControlador, null, this);
    }//GEN-LAST:event_cadastrarNovaEmpresaAuxButtonAuxActionPerformed

    private void cadastrarNovoAssociadoListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoAssociadoListaButtonActionPerformed
       // new fichaAssociadoForm(principalControlador, null, this);
    }//GEN-LAST:event_cadastrarNovoAssociadoListaButtonActionPerformed

    private void editarAssociadoListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAssociadoListaButtonActionPerformed

        //Pega a tabela e transforma num modelo o qual podemos manipular seu conteudo
        modeloTabelaAssociados model = (modeloTabelaAssociados) jTableAssociados.getModel();
        //Validamos o resultado
        if (jTableAssociados.getSelectedRow() != -1) {
            //Pegamos os dados selecionados na tabela e encontramos o modelo na lista de associados
            Associados ass = principalControlador.getControladorAssociados().buscarAssociado((String) model.getValueAt(jTableAssociados.getSelectedRow(), 0));
            if (ass != null) {
              // new fichaAssociadoForm(principalControlador, ass, this);//iniciamos a tela enviando um modelo
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar um associado na tabela primeiro!");
        }
    }//GEN-LAST:event_editarAssociadoListaButtonActionPerformed

    private void excluirAssociadoListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAssociadoListaButtonActionPerformed
        //Pega a tabela e transforma num modelo o qual podemos manipular seu conteudo
        modeloTabelaAssociados model = (modeloTabelaAssociados) jTableAssociados.getModel();
        //Validamos o resultado
        if (jTableAssociados.getSelectedRow() != -1) {
            //Pegamos os dados selecionados na tabela e encontramos o modelo na lista de associados
            principalControlador.getControladorAssociados().removeAssociado((String) model.getValueAt(jTableAssociados.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar um associado na tabela primeiro!");
        }
        preencherTabela("Associados", jTableAssociados);
    }//GEN-LAST:event_excluirAssociadoListaButtonActionPerformed

    private void cadastrarEmpresaListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEmpresaListaButtonActionPerformed
       // new fichaEmpresaForm(principalControlador, null, this);
    }//GEN-LAST:event_cadastrarEmpresaListaButtonActionPerformed

    private void editarEmpresaListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpresaListaButtonActionPerformed
        //Pega a tabela e transforma num modelo o qual podemos manipular seu conteudo
        modeloTabelaEmpresas model = (modeloTabelaEmpresas) jTableEmpresas.getModel();
        //Validamos o resultado
        if (jTableEmpresas.getSelectedRow() != -1) {
            //Pegamos os dados selecionados na tabela e encontramos o modelo na lista de associados
            Empresas emp = principalControlador.getControladorEmpresas().buscarEmpresa((String) model.getValueAt(jTableEmpresas.getSelectedRow(), 0));
            if (emp != null) {
               //new fichaEmpresaForm(principalControlador, emp, this);//iniciamos a tela enviando um modelo
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma empresa na tabela primeiro!");
        }
    }//GEN-LAST:event_editarEmpresaListaButtonActionPerformed

    private void excluirEmpresaListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEmpresaListaButtonActionPerformed
        //Pega a tabela e transforma num modelo o qual podemos manipular seu conteudo
        modeloTabelaEmpresas model = (modeloTabelaEmpresas) jTableEmpresas.getModel();
        //Validamos o resultado
        if (jTableEmpresas.getSelectedRow() != -1) {
            //Pegamos os dados selecionados na tabela e encontramos o modelo na lista de associados
            principalControlador.getControladorEmpresas().removeEmpresa((String) model.getValueAt(jTableEmpresas.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma empresa na tabela primeiro!");
        }
        preencherTabela("Empresas", jTableEmpresas);
    }//GEN-LAST:event_excluirEmpresaListaButtonActionPerformed

    public void preencherTabela(String nome, JTable table) {
        //Inicializa os modelos existentes
        modeloTabelaAssociados modeloAss = null;
        modeloTabelaEmpresas modeloEmp = null;

        //Valida o tipo da tabela e preenche
        switch (nome) {
            case "Associados":
                modeloAss = new modeloTabelaAssociados(principalControlador.getControladorAssociados().getListaAssociados());
                if (modeloAss != null) {
                    table.setModel(modeloAss);
                    table.getTableHeader().setReorderingAllowed(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao procurar a tabela para preenchimento!!!", "ERROR!", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "Empresas":
                modeloEmp = new modeloTabelaEmpresas(principalControlador.getControladorEmpresas().getListaEmpresas());
                if (modeloEmp != null) {
                    table.setModel(modeloEmp);
                    table.getTableHeader().setReorderingAllowed(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao procurar a tabela para preenchimento!!!", "ERROR!", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
        //jTableAssociados.setAutoResizeMode(jTableAssociados.AUTO_RESIZE_OFF);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarNovoMaterialVendaButton;
    private javax.swing.JButton adicionarItemCompraButton;
    private javax.swing.JButton adicionarItemVendaButton;
    private javax.swing.JComboBox<String> associadoComboBox;
    private javax.swing.JButton associadosButton;
    private javax.swing.JPanel associadosPanel;
    private javax.swing.JButton cadastrarAssociadoCompraButton;
    private javax.swing.JButton cadastrarEmpresaListaButton;
    private javax.swing.JButton cadastrarNovaEmpresaAuxButtonAux;
    private javax.swing.JButton cadastrarNovoAssociadoListaButton;
    private javax.swing.JButton cadastrarNovoMaterialCompraButton;
    private javax.swing.JButton cancelarCompraButton;
    private javax.swing.JButton cancelarVendaButton;
    private javax.swing.JButton comprarButton;
    private javax.swing.JPanel comprarPanel;
    private javax.swing.JButton confirmarCompraButton;
    private javax.swing.JButton confirmarVendaButton;
    private javax.swing.JButton editarAssociadoListaButton;
    private javax.swing.JButton editarEmpresaListaButton;
    private javax.swing.JButton empresasButton;
    private javax.swing.JComboBox<String> empresasComboBox;
    private javax.swing.JPanel empresasPanel;
    private javax.swing.JButton excluirAssociadoListaButton;
    private javax.swing.JButton excluirEmpresaListaButton;
    private javax.swing.JTextArea infoCompraTextArea;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JTextArea infoVendaTextArea;
    private javax.swing.JLabel infoVendaTotalAReceberLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTableAssociados;
    private javax.swing.JTable jTableEmpresas;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JComboBox<String> materialCompraComboBox;
    private javax.swing.JComboBox<String> materialVendaComboBox;
    private javax.swing.JPanel menuButtonsPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton pagIniButton;
    private javax.swing.JPanel pagIniPanel;
    private javax.swing.JTextField precoItemCompraTextField;
    private javax.swing.JTextField precoItemVendaTextField;
    private javax.swing.JTextField precoTotalItemTextField;
    private javax.swing.JTextField precoTotalItemVendaTextField;
    private javax.swing.JTextField quantidadeItemCompraTextField;
    private javax.swing.JTextField quantidadeItemVendaTextField;
    private javax.swing.JButton relatoriosButton;
    private javax.swing.JPanel relatoriosPanel;
    private javax.swing.JButton sairButton;
    private javax.swing.JLabel totalAPagarLabel;
    private javax.swing.JButton venderButton;
    private javax.swing.JPanel venderPanel;
    // End of variables declaration//GEN-END:variables

    //Getters----------------------------------------------------
    public JTable getjTableAssociados() {
        return jTableAssociados;
    }

    public JTable getjTableEmpresas() {
        return jTableEmpresas;
    }
}
